[package]
name = "access-control"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "my_binary"
path = "src/lib.rs"

[lib]
name = "access_control"
crate-type = ["cdylib"]

[dependencies]

[build-dependencies]

[target.armv7-unknown-linux-gnueabihf]
rustflags = ["-C", "target-feature=+vfp3,-d32"]
